jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - run:
          command: npm test
          name: Run tests
orbs:
  node: 'circleci/node@3.0.0' 
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
