jobs:
  test:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run:
        name: Install yarn
        command: npm install yarn
      - run:
        name: Run tests
        command: yarn test
orbs:
  node: 'circleci/node@3.0.0' 
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test
