version: 2.1
orbs:
  node: 'circleci/node@4.0.0'
jobs:
  test:
    docker: 
      - image: cimg/node:14.10.1 
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn test 
workflows:
  test_my_app:
    jobs:
      - test
